//
// Created by Charlie Culbert on 9/11/25.
//

#ifndef CONSOLEAPPSTATICPLAYER_BUFFEREDAUDIOFILEPLAYERMODULE_H
#define CONSOLEAPPSTATICPLAYER_BUFFEREDAUDIOFILEPLAYERMODULE_H


class BufferedAudioFilePlayerModule {
};


#endif //CONSOLEAPPSTATICPLAYER_BUFFEREDAUDIOFILEPLAYERMODULE_H