services:
  linux-dev:
    build: .
    volumes:
      - ../:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    # Audio devices don't exist on macOS, so skip them
    # devices:
    #   - /dev/snd:/dev/snd
    environment:
      - DISPLAY=${DISPLAY:-}
    command: /bin/bash